import React, { FC } from "react";
import { StyleProp, StyleSheet, ViewProps } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useTheme } from "@/contexts/ThemeProvider";

export const AllIcons = [
    "accessibility-outline",
    "add-outline",
    "airplane-outline",
    "alarm-outline",
    "albums-outline",
    "alert-outline",
    "american-football-outline",
    "analytics-outline",
    "aperture-outline",
    "archive-outline",
    "arrow-back-outline",
    "arrow-down-outline",
    "arrow-forward-outline",
    "arrow-redo-outline",
    "arrow-undo-outline",
    "arrow-up-outline",
    "at-outline",
    "attach-outline",
    "backspace-outline",
    "bag-outline",
    "bag-add-outline",
    "bag-check-outline",
    "bag-handle-outline",
    "bag-remove-outline",
    "balloon-outline",
    "ban-outline",
    "bandage-outline",
    "bar-chart-outline",
    "barbell-outline",
    "barcode-outline",
    "baseball-outline",
    "basket-outline",
    "basketball-outline",
    "battery-charging-outline",
    "battery-dead-outline",
    "battery-full-outline",
    "battery-half-outline",
    "beaker-outline",
    "bed-outline",
    "beer-outline",
    "bicycle-outline",
    "bluetooth-outline",
    "boat-outline",
    "body-outline",
    "bonfire-outline",
    "bowling-ball-outline",
    "briefcase-outline",
    "browsers-outline",
    "brush-outline",
    "bug-outline",
    "build-outline",
    "bulb-outline",
    "bus-outline",
    "business-outline",
    "cafe-outline",
    "calculator-outline",
    "calendar-outline",
    "calendar-clear-outline",
    "calendar-number-outline",
    "call-outline",
    "camera-outline",
    "camera-reverse-outline",
    "car-outline",
    "car-sport-outline",
    "card-outline",
    "cart-outline",
    "cash-outline",
    "cellular-outline",
    "chatbox-outline",
    "chatbox-ellipses-outline",
    "chatbubble-outline",
    "chatbubble-ellipses-outline",
    "chatbubbles-outline",
    "checkbox-outline",
    "checkmark-outline",
    "checkmark-done-outline",
    "chevron-back-outline",
    "chevron-collapse-outline",
    "chevron-down-outline",
    "chevron-expand-outline",
    "chevron-forward-outline",
    "chevron-up-outline",
    "clipboard-outline",
    "close-outline",
    "cloud-outline",
    "cloud-done-outline",
    "cloud-download-outline",
    "cloud-offline-outline",
    "cloud-upload-outline",
    "cloudy-outline",
    "cloudy-night-outline",
    "code-outline",
    "code-download-outline",
    "code-slash-outline",
    "code-working-outline",
    "cog-outline",
    "color-fill-outline",
    "color-filter-outline",
    "color-palette-outline",
    "color-wand-outline",
    "compass-outline",
    "construct-outline",
    "contract-outline",
    "contrast-outline",
    "copy-outline",
    "create-outline",
    "crop-outline",
    "cube-outline",
    "cut-outline",
    "desktop-outline",
    "diamond-outline",
    "dice-outline",
    "disc-outline",
    "document-outline",
    "document-attach-outline",
    "document-lock-outline",
    "document-text-outline",
    "documents-outline",
    "download-outline",
    "duplicate-outline",
    "ear-outline",
    "earth-outline",
    "easel-outline",
    "egg-outline",
    "ellipse-outline",
    "enter-outline",
    "exit-outline",
    "expand-outline",
    "extension-puzzle-outline",
    "eye-outline",
    "eye-off-outline",
    "eyedrop-outline",
    "fast-food-outline",
    "female-outline",
    "file-tray-outline",
    "file-tray-full-outline",
    "file-tray-stacked-outline",
    "film-outline",
    "filter-outline",
    "finger-print-outline",
    "fish-outline",
    "fitness-outline",
    "flag-outline",
    "flame-outline",
    "flash-outline",
    "flash-off-outline",
    "flashlight-outline",
    "flask-outline",
    "flower-outline",
    "folder-outline",
    "folder-open-outline",
    "football-outline",
    "footsteps-outline",
    "funnel-outline",
    "game-controller-outline",
    "gift-outline",
    "git-branch-outline",
    "git-commit-outline",
    "git-compare-outline",
    "git-merge-outline",
    "git-network-outline",
    "git-pull-request-outline",
    "glasses-outline",
    "globe-outline",
    "golf-outline",
    "grid-outline",
    "hammer-outline",
    "hand-left-outline",
    "hand-right-outline",
    "happy-outline",
    "hardware-chip-outline",
    "headset-outline",
    "heart-outline",
    "heart-dislike-outline",
    "heart-half-outline",
    "help-outline",
    "help-buoy-outline",
    "home-outline",
    "hourglass-outline",
    "ice-cream-outline",
    "id-card-outline",
    "image-outline",
    "images-outline",
    "infinite-outline",
    "information-outline",
    "invert-mode-outline",
    "journal-outline",
    "key-outline",
    "keypad-outline",
    "language-outline",
    "laptop-outline",
    "layers-outline",
    "leaf-outline",
    "library-outline",
    "link-outline",
    "list-outline",
    "locate-outline",
    "location-outline",
    "lock-closed-outline",
    "lock-open-outline",
    "log-in-outline",
    "log-out-outline",
    "magnet-outline",
    "mail-outline",
    "mail-open-outline",
    "mail-unread-outline",
    "male-outline",
    "male-female-outline",
    "man-outline",
    "map-outline",
    "medal-outline",
    "medical-outline",
    "medkit-outline",
    "megaphone-outline",
    "menu-outline",
    "mic-outline",
    "mic-off-outline",
    "moon-outline",
    "move-outline",
    "musical-note-outline",
    "musical-notes-outline",
    "navigate-outline",
    "newspaper-outline",
    "notifications-outline",
    "notifications-off-outline",
    "nuclear-outline",
    "nutrition-outline",
    "open-outline",
    "options-outline",
    "pause-outline",
    "paw-outline",
    "pencil-outline",
    "people-outline",
    "phone-portrait-outline",
    "pie-chart-outline",
    "pin-outline",
    "pint-outline",
    "pizza-outline",
    "planet-outline",
    "play-outline",
    "play-back-outline",
    "play-forward-outline",
    "play-skip-back-outline",
    "play-skip-forward-outline",
    "podium-outline",
    "power-outline",
    "pricetag-outline",
    "pricetags-outline",
    "print-outline",
    "prism-outline",
    "pulse-outline",
    "push-outline",
    "qr-code-outline",
    "radio-outline",
    "radio-button-off-outline",
    "radio-button-on-outline",
    "rainy-outline",
    "reader-outline",
    "receipt-outline",
    "recording-outline",
    "refresh-outline",
    "reload-outline",
    "resize-outline",
    "restaurant-outline",
    "ribbon-outline",
    "rocket-outline",
    "rose-outline",
    "sad-outline",
    "save-outline",
    "scale-outline",
    "scan-outline",
    "school-outline",
    "search-outline",
    "send-outline",
    "server-outline",
    "settings-outline",
    "shapes-outline",
    "share-outline",
    "share-social-outline",
    "shield-outline",
    "shield-checkmark-outline",
    "shield-half-outline",
    "shirt-outline",
    "shuffle-outline",
    "skull-outline",
    "snow-outline",
    "sparkles-outline",
    "speedometer-outline",
    "square-outline",
    "star-outline",
    "star-half-outline",
    "stats-chart-outline",
    "stop-outline",
    "stopwatch-outline",
    "storefront-outline",
    "subway-outline",
    "sunny-outline",
    "swap-horizontal-outline",
    "swap-vertical-outline",
    "sync-outline",
    "telescope-outline",
    "tennisball-outline",
    "terminal-outline",
    "text-outline",
    "thermometer-outline",
    "thumbs-down-outline",
    "thumbs-up-outline",
    "thunderstorm-outline",
    "ticket-outline",
    "time-outline",
    "timer-outline",
    "today-outline",
    "toggle-outline",
    "trail-sign-outline",
    "train-outline",
    "transgender-outline",
    "trash-outline",
    "trash-bin-outline",
];

export type IconColor =
    | "onPrimary"
    | "error"
    | "warning"
    | "success"
    | "error"
    | "onBackground"
    | "onSecondary"
    | "complementary"
    | "info";

interface IconProps {
    icon: string;
    size: number;
    color?: IconColor;
    style?: StyleProp<ViewProps>;
}

const Icon: FC<IconProps> = ({ icon, size, color = "textOnPrimary", style }) => {
    const theme = useTheme();

    const calculateIconColor = (color: string) => {
        switch (color) {
            case "onPrimary":
                return theme.current.colors.textOnPrimary;
            case "error":
                return theme.current.colors.error;
            case "warning":
                return theme.current.colors.warning;
            case "success":
                return theme.current.colors.success;
            case "info":
                return theme.current.colors.info;
            case "onSecondary":
                return theme.current.colors.textOnSecondary;
            case "complementary":
                return theme.current.colors.complementary;
            default:
                return theme.current.colors.textOnBackground;
        }
    };

    // NOTE: When adding other icon sets, handle them here
    // but names returned and set should start with this set name like 'fontawersome-add-outline'

    const outlineIcon =
        icon.startsWith("logo-") || icon.endsWith("-outline")
            ? icon
            : icon.endsWith("-sharp")
              ? icon.replace(/-sharp$/, "-outline")
              : `${icon}-outline`;

    return (
        <Ionicons
            size={size}
            name={outlineIcon as keyof typeof Ionicons.glyphMap}
            style={[styles.icon, style]}
            color={calculateIconColor(color)}
        />
    );
};

export default Icon;

const styles = StyleSheet.create({
    icon: {
        alignItems: "center",
        justifyContent: "center",
    },
});
